export const locale_token_multiplier: Partial<Record<string, number>> = {
  af: 1.3, // Afrikaans
  sq: 1.3, // Albanian
  am: 1.3, // Amharic
  ar: 1.3, // Arabic
  hy: 1.3, // Armenian
  az: 1.3, // Azerbaijani
  eu: 1.3, // Basque
  be: 1.3, // Belarusian
  bn: 1.5, // Bengali
  bs: 1.3, // Bosnian
  bg: 1.3, // Bulgarian
  ca: 1.3, // Catalan
  ceb: 1.3, // Cebuano
  zh: 2.0, // Chinese (Simplified)
  "zh-TW": 2.0, // Chinese (Traditional)
  co: 1.3, // Corsican
  hr: 1.3, // Croatian
  cs: 1.3, // Czech
  da: 1.3, // Danish
  nl: 1.3, // Dutch
  en: 1.0, // English
  eo: 1.3, // Esperanto
  et: 1.3, // Estonian
  fi: 1.5, // Finnish
  fr: 1.5, // French
  fy: 1.3, // Frisian
  gl: 1.3, // Galician
  ka: 1.5, // Georgian
  de: 1.5, // German
  el: 1.5, // Greek
  gu: 1.5, // Gujarati
  ht: 1.3, // Haitian Creole
  ha: 1.3, // Hausa
  haw: 1.3, // Hawaiian
  he: 1.3, // Hebrew
  hi: 1.5, // Hindi
  hmn: 1.5, // Hmong
  hu: 1.3, // Hungarian
  is: 1.3, // Icelandic
  ig: 1.3, // Igbo
  id: 1.3, // Indonesian
  ga: 1.3, // Irish
  it: 1.5, // Italian
  ja: 2.0, // Japanese
  jw: 1.3, // Javanese
  kn: 1.5, // Kannada
  kk: 1.3, // Kazakh
  km: 1.5, // Khmer
  rw: 1.3, // Kinyarwanda
  ko: 2.0, // Korean
  ku: 1.5, // Kurdish
  ky: 1.3, // Kyrgyz
  lo: 1.5, // Lao
  la: 1.3, // Latin
  lv: 1.3, // Latvian
  lt: 1.3, // Lithuanian
  lb: 1.3, // Luxembourgish
  mk: 1.3, // Macedonian
  mg: 1.3, // Malagasy
  ms: 1.3, // Malay
  ml: 1.5, // Malayalam
  mt: 1.3, // Maltese
  mi: 1.3, // Maori
  mr: 1.5, // Marathi
  mn: 1.3, // Mongolian
  my: 1.5, // Myanmar (Burmese)
  ne: 1.5, // Nepali
  no: 1.3, // Norwegian
  ny: 1.3, // Nyanja (Chichewa)
  or: 1.5, // Odia
  ps: 1.5, // Pashto
  fa: 1.5, // Persian
  pl: 1.3, // Polish
  pt: 1.5, // Portuguese
  pa: 1.5, // Punjabi
  ro: 1.3, // Romanian
  ru: 1.3, // Russian
  sm: 1.3, // Samoan
  gd: 1.3, // Scots Gaelic
  sr: 1.3, // Serbian
  st: 1.3, // Sesotho
  sn: 1.3, // Shona
  sd: 1.5, // Sindhi
  si: 1.5, // Sinhala
  sk: 1.3, // Slovak
  sl: 1.3, // Slovenian
  so: 1.3, // Somali
  es: 1.5, // Spanish
  su: 1.3, // Sundanese
  sw: 1.3, // Swahili
  sv: 1.3, // Swedish
  tl: 1.3, // Tagalog (Filipino)
  tg: 1.3, // Tajik
  ta: 1.5, // Tamil
  tt: 1.3, // Tatar
  te: 1.5, // Telugu
  th: 1.5, // Thai
  tr: 1.3, // Turkish
  tk: 1.3, // Turkmen
  uk: 1.3, // Ukrainian
  ur: 1.5, // Urdu
  ug: 1.3, // Uyghur
  uz: 1.3, // Uzbek
  vi: 1.5, // Vietnamese
  cy: 1.3, // Welsh
  xh: 1.3, // Xhosa
  yi: 1.3, // Yiddish
  yo: 1.3, // Yoruba
  zu: 1.3, // Zulu
};
